### PR TITLE
improve email validation regex in Login and SignUp screens

### PR DESCRIPTION
**Pull request by Richie911**
# Description

This PR is aimed at improving the regex for email validation to include emails like city.texas@gmail.com

### CODE REVIEW

**Review by Thenlie — APPROVED** [review]
Great work! The regex seems to work well on my end. My only improvement suggestion is that we make the regex shared between the login and signup screen. Likely placed in https://github.com/Thenlie/Streamability/blob/main/src/helpers/validationUtils.ts. 

I am more than happy to merge this PR as is, but let me know if you would like to make thia change.

**Comment by Richie911** [comment]
@Thenlie, that makes sense; I will get that done asap

**Comment by Richie911** [comment]
@Thenlie , the changes are ready

**Review by Thenlie — APPROVED** [review]

**Comment by Thenlie** [comment]
@Richie911 The changes look great! The CI check is failing though due to the TODO file being out of date. Please run `npm run todo-ci` and commit the result. I will get this merged after that. Thanks!

**Comment by Richie911** [comment]
@Thenlie , I did run the npm run todo-ci and committed the changes but the CI still failed

**Comment by Thenlie** [comment]
> I did run the npm run todo-ci and committed the changes but the CI still failed

There are still some issues with the CI on fork PRs, but we can ignore the other failures for now. Thank you!

**Pull request merged**
