### PR TITLE
View state local storage

### LINKED ISSUE #484: 🏗 Store view state in local storage
Currently the view state will switch back to list on refresh. We should store the state in local storage so it defaults to what the user had last selected.

### PR DESCRIPTION
**Pull request by Thenlie**
The view state will now persist through refresh and page close.

Closes #484

### CODE REVIEW

**Review by phillpeters — COMMENTED** [review]
~~This has a lot of the same changes as the pull request for the logo...am I seeing that right?~~

Scratch that, not sure what my phone was showing me.

**Comment by Thenlie** [comment]
> This has a lot of the same changes as the pull request for the logo...am I seeing that right?

I had branched off of the branch on the previous pull request 😅 . I just updated to be off develop so if you look again you will see just these changes.

**Comment by phillpeters** [comment]
Lol too many things happening in real time😂

**Comment by phillpeters** [comment]
@Thenlie the first time around I left a comment without approving. Now I don't see an option to approve anymore.

**Comment by Thenlie** [comment]
> @Thenlie the first time around I left a comment without approving. Now I don't see an option to approve anymore.

@phillpeters I re-requested

**Review by phillpeters — APPROVED** [review]
👍🏻

**Pull request merged**
