### PR TITLE
feat: add crew section to ShowDetailsScreen

### PR DESCRIPTION
**Pull request by Richie911**
# Description
This PR aims to separate crew and casts

### CODE REVIEW

**Comment by Richie911** [comment]
@Thenlie I will get the first recommendation done asap.

**Comment by Richie911** [comment]
@Thenlie , I believe this is what we want correct?

**Comment by Richie911** [comment]
the number 2 is also ready

**Comment by Thenlie** [comment]
> I believe this is what we want correct?

**Comment by Thenlie** [comment]
>  I believe this is what we want correct?

Yes this looks great!

**Pull request merged**
