### PR TITLE
47 feat react router

### LINKED ISSUE #47: 📝 Implement React Router with a few basic routes
# Add React Router

Since there will be a handful of pages in the app, React Router will be a nice package to use. We should use the most current stable release.

## Acceptance Criteria

- [x] React Router v6.4.3 implemented
    - [x]  Dependency errors resolved
    - [x] NPM warns resolved
- [x] 1-2 sample routes created and working

## Resources 

https://reactrouter.com/en/main/start/overview

### PR DESCRIPTION
**Pull request by Thenlie**
# React Router Added

React Router v6.4.3 has been added to the project. This API is quite a bit different than the one we used in the bootcamp so be sure to check out the [docs!](https://reactrouter.com/en/main/start/overview) 

I set up some basic pages so routes could be tested. While these are just filler pages, I think they will be the routes we actually use. So the files should not need to be removed, just added to. 

Below are screenshots of all the routes in action. Worth noting that the `AppWrapper` component wraps the entire app (which is why you see "Streamability" on every page). This could be nice for a header/footer or other things global to the application.

Closes #47 

## 📸  Screenshots

image

image

image

### CODE REVIEW

**Comment by Thenlie** [comment]
❌ While the build succeeds, the routes are not accessible on the deployment. Standby

**Review by maxh1231 — DISMISSED** [review]
Beep boop browser router beep boop

**Comment by Thenlie** [comment]
✅  Adding in a `vercel.json` file in commit [4cbb86d](https://github.com/Thenlie/Streamability/pull/48/commits/4cbb86dbee4adef88d48e6ed76b660c6bb597536) did the trick. Deployment now works as intended.

**Review by maxh1231 — APPROVED** [review]
Found it

**Pull request merged**
